/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema;

/**
 *
 * @author Rodrigo
 */
public class FCrearCuentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form CuentaC
     */
    private CrearCuenta crearCuenta;
    private FPrincipal fPrincipal;
    public FCrearCuentas() {
        initComponents();
        crearCuenta = new CrearCuenta();
        jtfDebe.setEnabled(false);
        jtfHaber.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfDescripcion = new javax.swing.JTextField();
        jcbTipoCuenta = new javax.swing.JComboBox();
        jtfDebe = new javax.swing.JTextField();
        jtfHaber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear cuenta");

        jtfDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDescripcionActionPerformed(evt);
            }
        });

        jcbTipoCuenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Activo (A)", "Pasivo (P)", "Capital (K)" }));
        jcbTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoCuentaActionPerformed(evt);
            }
        });

        jtfDebe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfDebeMouseClicked(evt);
            }
        });
        jtfDebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDebeActionPerformed(evt);
            }
        });

        jtfHaber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfHaberMouseClicked(evt);
            }
        });
        jtfHaber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHaberActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripción");

        jLabel5.setText("Tipo de Cuenta");

        jLabel3.setText("Debe");

        jLabel4.setText("Haber");

        jLabel6.setText("ID");

        jlbID.setText("-");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(44, 44, 44))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfHaber, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDebe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jcbTipoCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jlbID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jtfDebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfHaber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4)))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDescripcionActionPerformed

    }//GEN-LAST:event_jtfDescripcionActionPerformed

    private void jcbTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoCuentaActionPerformed
        if ( jcbTipoCuenta.getItemCount() == 4 && jcbTipoCuenta.getSelectedIndex() != 0  ){
            jcbTipoCuenta.removeItemAt(0);
            mostrarId();
        }else
        if (jcbTipoCuenta.getItemCount() == 3)
        mostrarId();
    }//GEN-LAST:event_jcbTipoCuentaActionPerformed

    private void jtfDebeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfDebeMouseClicked

    }//GEN-LAST:event_jtfDebeMouseClicked

    private void jtfDebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDebeActionPerformed

    }//GEN-LAST:event_jtfDebeActionPerformed

    private void jtfHaberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfHaberMouseClicked

    }//GEN-LAST:event_jtfHaberMouseClicked

    private void jtfHaberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHaberActionPerformed

    }//GEN-LAST:event_jtfHaberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String monto;
        if (jtfDebe.isEnabled())
        //El monto se cargará
        monto = jtfDebe.getText();
        else
        //El monto se abonará
        monto = jtfHaber.getText();
        if ( crearCuenta.crearCuenta(jlbID.getText(),jtfDescripcion.getText(),
            jcbTipoCuenta.getSelectedIndex(),monto, new java.util.Date()) )
    limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void deshabilitar(int i){
    if ( i == 1 ){
        jtfHaber.setText("");
        jtfHaber.setEnabled(false);
        jtfDebe.setEnabled(true);        
    }else{
        jtfDebe.setText("");
        jtfDebe.setEnabled(false);
        jtfHaber.setEnabled(true);        
    }   

}
    private void limpiar(){
        jtfDebe.setText("");
        jtfHaber.setText("");
        jlbID.setText("");
        jtfDescripcion.setText("");                
        jcbTipoCuenta.removeAllItems();
        jcbTipoCuenta.addItem("Seleccionar");
        jcbTipoCuenta.addItem("Activo (A)");
        jcbTipoCuenta.addItem("Pasivo (P)");
        jcbTipoCuenta.addItem("Capital (K)");
        jcbTipoCuenta.setSelectedIndex(0);
    }
    
    public void mostrarId(){
        int tipoCuenta = jcbTipoCuenta.getSelectedIndex();
        String idGenerado =  ( tipoCuenta + 1 ) + "";
        jlbID.setText(idGenerado + "." +
                ServicioBD.getCorrelativo(Cuenta.getTipoChar(tipoCuenta)) );
        deshabilitar(tipoCuenta);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox jcbTipoCuenta;
    private javax.swing.JLabel jlbID;
    private javax.swing.JTextField jtfDebe;
    private javax.swing.JTextField jtfDescripcion;
    private javax.swing.JTextField jtfHaber;
    // End of variables declaration//GEN-END:variables
}
