/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class FTransaccion extends javax.swing.JInternalFrame {

    /**
     * Creates new form FTransaccion
     */
    Connection conexion;
    ResultSet res;
    Statement st;
    
    public FTransaccion() {
        initComponents();
        cargarCuentas();
    }

    private void cargarCuentas()
    {
        conexion = ConexionBD.Conectar();
        try{
        st = conexion.createStatement();
        res = st.executeQuery("SELECT id, nombre FROM CUENTAS EXCEPT SELECT c2.id, c2.nombre "
                + "FROM cuentas AS c1 INNER JOIN cuentas AS c2 ON c1.idpadre=c2.id");
        while(res.next())
        {
            String cuenta = res.getString("id") + " " + res.getString("nombre");
            System.out.println(cuenta);
        }
        }catch(Exception e){JOptionPane.showMessageDialog(null, "ERROR \n"+e);}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardar = new javax.swing.JButton();
        fecha = new org.freixas.jcalendar.JCalendarCombo();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Transacción");

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(guardar)
                        .add(196, 196, 196))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(fecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(fecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 210, Short.MAX_VALUE)
                .add(guardar)
                .add(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        /*
         * 
         *  st = conexion.prepareStatement("INSERT INTO transacciones (id, fecha,"
                + " descripcion) VALUES (?,?,?)");
            st.setDate(1, new java.sql.Date(fecha.getDate().getTime()));
            st.setString(2, numcor);
            st.setString(3, descripcion.getText());
            st.executeUpdate();
        * 
        * */
    }//GEN-LAST:event_guardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.freixas.jcalendar.JCalendarCombo fecha;
    private javax.swing.JButton guardar;
    // End of variables declaration//GEN-END:variables
}
